let score = false

//console.log(typeof score)
//console.log(typeof (score))

let valueInNumber = Number(score)
//console.log(typeof valueInNumber)
//console.log(valueInNumber);


// "33" => 33
// "##abc" => NaN
// "true" => 1; false => 0

let isLoggedIn = "Satya"

let booleanIsLoggrdIn = Boolean(isLoggedIn)

// console.log(booleanIsLoggrdIn)

// 1 => true ; 0 => false
// "" => false ; "Satya" => true
// "hitesh" => true

/*let someNumber = 33

let stringNumber = String(someNumber)
console.log(stringNumber);
console.log(typeof stringNumber);*/


/************************ Operations ****************************/

let value = 3
let negValue = -value

// console.log(negValue);

// console.log(2+2);
// console.log(2-2);
// console.log(2*2);
// console.log(2**3);
// console.log(2/3);
// console.log(2%3);

let str1 = "hello"
let str2 = " Satya"

// let str3 = str1 + str2;
// console.log(str3)


// console.log("1" + 2); // 12
// console.log(1 + "2"); // 12
// console.log("1" + 2 + 2) // 122
// console.log(1 + 2 + "2") // 32

// console.log(true) // true
// console.log(+""); //0


let gameCounter = 100
gameCounter++;
console.log(gameCounter); //101
