let score = false

//console.log(typeof score)
//console.log(typeof (score))

let valueInNumber = Number(score)
//console.log(typeof valueInNumber)
//console.log(valueInNumber);


// "33" => 33
// "##abc" => NaN
// "true" => 1; false => 0

let isLoggedIn = "Satya"

let booleanIsLoggrdIn = Boolean(isLoggedIn)

// console.log(booleanIsLoggrdIn)

// 1 => true ; 0 => false
// "" => false ; "Satya" => true
// "hitesh" => true

let someNumber = 33

let stringNumber = String(someNumber)
console.log(stringNumber);
console.log(typeof stringNumber);